// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcSleep.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MvcSleep.Migrations
{
    [DbContext(typeof(MvcSleepDataContext))]
    [Migration("20200907030534_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MvcSleep.Models.MyRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("SleepDataModelId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SleepDataModelId");

                    b.ToTable("MyRecords");
                });

            modelBuilder.Entity("MvcSleep.Models.SleepDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("SleepDataAnnotation")
                        .HasColumnType("text");

                    b.Property<string>("SleepDataName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SleepData");
                });

            modelBuilder.Entity("MvcSleep.Models.MyRecords", b =>
                {
                    b.HasOne("MvcSleep.Models.SleepDataModel", null)
                        .WithMany("SleepDataRecords")
                        .HasForeignKey("SleepDataModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
